### ISSUE TITLE
Ember: Crawling template dependencies.

### ISSUE THREAD

**Issue by amiller-gh** [linkedin/css-blocks#125]
We currently use the `glimmer-analyzer` package to [crawl a Glimmer project's template dependency structure](https://github.com/linkedin/css-blocks/blob/master/packages/%40css-blocks/glimmer/src/Analyzer.ts#L13). I don't know if this same plugin will work for greenfield ember apps.

If this package *does* work to analyze dependency trees of Ember app templates, we will need to add special logic in `@css-blocks/ember-cli` to appropriately pass the `Project` to our Analyzer depending on if it is an Ember or Glimmer app.

If this package *does not* work to analyze template dependencies, we will need to figure out what other methods we can use in Ember to achieve the same effect.

This is a very open ended ticket and will take some exploration.

**Comment by ef4** [comment]
In todays ember apps, it's not possible to statically detect unused components, because there are too many ways to dynamically depend on one. But I don't think that makes css-blocks any less useful -- I think it's fine to treat every component as a valid "entry point" from css-blocks' perspective. We would still get most of the benefits.

Work is underway to port more of standalone-glimmer's static resolution into Ember, at which point we could do the more aggressive dead-component-elimination thing, for apps that opt out of all the classic dynamic behaviors.
