### ISSUE TITLE
Ember: Require components with an associated Block file to be "tag-less" components?

### ISSUE THREAD

**Issue by amiller-gh** [linkedin/css-blocks#127]
In Ember, we may want to add validation that all components with an associated Block file are tag-less components. This will prevent unexpected styling behavior and restrict the javascript footprint where users may accidentally interact with class names directly.

However, there may be better ways to enforce this and validate it other than a built time linter for `tagName: ''` in every CSS Blocks component. Ex: at rewrite time we can inject `tagName: ''` into every CSS Blocks associated component so the user doesn't have to.

Lets have this design discussion in this issue.

**Comment by ef4** [comment]
Since glimmer components are already landing in Ember (you can use them today in 3.1 for the template-only case) another way of meeting this requirement is just to say that css-blocks only works with (1) glimmer components or (2) classic components with `tagName: ''`.

Over time we very much want the normal thing that everybody is using to be glimmer components.
