### ISSUE TITLE
Unable to install - No matching version found for @opticss/template-api@^0.2.0

### ISSUE THREAD

**Issue by vcicmanec** [linkedin/css-blocks#180]
When I try to install css-blocks by `npm i -D css-blocks` installation fails with this error

`npm ERR! code ETARGET`
`npm ERR! notarget No matching version found for @opticss/template-api@^0.2.0`
...
`npm ERR! notarget It was specified as a dependency of 'css-blocks'`

Seems like wrong dependency entry was published.

I'm running node 10.1.0 and npm 6.1.0 in WSL. 
Install fails also with npm 5.6.0 and node 10.1.0 in windows.

**Comment by amiller-gh** [comment]
Well that would be because `@opticss/template-api@0.2.0` doesn't exist :) Only 0.3.0 has ever been published, and because the package is pre-1.0 the `^` means NPM won't automatically grab the latest minor: https://www.npmjs.com/package/@opticss/template-api

However, thats not the actual problem. Integrating with css-blocks isn't quite as easy as simply installing it. You'll install both a build integration (like `@css-blocks/webpack`, or `@css-blocks/broccoli`) and a template integration (like `@css-blocks/jsx` or `@css-blocks/glimmer`) and consume each as their READMEs direct. This should be explained in the project documentation, please let us know if there are ways we can make it clearer!

The `css-blocks` package should actually contain nothing – we're squatting on the package name so someone else doesn't take it confuse people. However, it seems like some ancient version of CSS Blocks was accidentally published to it! I believe we have a plan to publish an empty project there with a `postinstall` hook that throws a nice, helpful "You probably didn't mean to install that package! Heres a link to the integration documentation" error to point users in the right direction. Sounds like we should get on that sooner rather than later!

**Comment by vcicmanec** [comment]
Ah, thanks for the explanation, I realized I will need @css-blocks/jsx , webpack etc, but thought this is a core package i will need in any case. Silly me.
